anggota/urls.py
from django.contrib import admin
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name="daftar_anggota"),
]

authentication/urls.py
from django.contrib import admin
from django.urls import path
from .views import login, register
app_name = 'authentication'


urlpatterns = [
    path('login_form/', login, name="login_form"),
    path('login/', login, name="login"),
    path('register/', register, name="register"),
]

komik/urls.py
from django.contrib import admin
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name="daftar_komik"),
]

myWebsite/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('anggota/', include('anggota.urls')),
    path('produk/', include('produk.urls')),
    path('komik/', include('komik.urls')),
    path('authentication/', include('authentication.urls'), name="authentication"),
    path('transaksi/', include('pinjam.urls')),
]

pinjam/urls.py
from django.contrib import admin
from django.urls import path
from .views import pinjam, baca

urlpatterns = [
    path('pinjam/', pinjam, name="pinjam"),
    path('baca/', baca, name="baca")
]

produk/urls.py
from django.contrib import admin
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name="daftar_produk"),
]

anggota/models.py
from django.db import models

# Create your models here.

authentication/models.py
from django.db import models

# Create your models here.

komik/models.py
from django.db import models

# Create your models here.

pinjam/models.py
from django.db import models

# Create your models here.

produk/models.py
from django.db import models

# Create your models here.

authentication/forms.py
from django import forms

class LoginForm(forms.Form):
    form_id = forms.CharField(label="Id", max_length=30)
    form_password = forms.CharField(widget=forms.PasswordInput())

anggota/views.py
from django.shortcuts import render
from django.db import connection
from django.core.paginator import Paginator

def index(request):
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to komik")
        cursor.execute("SELECT no_anggota, id, nama, alamat, tanggal_lahir, no_hp FROM anggota")
        data_anggota = dictfetchall(cursor)
    paginator = Paginator(data_anggota, 10)
    page = request.GET.get('page')
    data = paginator.get_page(page)
    return render(request, "daftar_anggota.html", {'data_anggota' : data})

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

authentication/views.py
from django.shortcuts import render
from .forms import LoginForm

# Create your views here.
def login_form(request):
    return  

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return form

def register(request):
    return render(request, 'register.html')

komik/views.py
from django.shortcuts import render
from django.db import connection

def index(request):
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to komik;"
                       "SELECT id, nama, jumlah, tipe_produk "
                       "FROM produk "
                       "WHERE tipe_produk = 'Komik';")
        data_komik = dictfetchall(cursor)
    return render(request, "daftar_komik.html", {'data_komik' : data_komik})

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

myWebsite/views.py
from django.shortcuts import render
from django.db import connection

def home(request):
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to komik;"
                       "SELECT nama, id "
                       "FROM anggota;")
        data_anggota = dictfetchall(cursor)
    return render(request, "homepage.html", {'data_anggota' : data_anggota})

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

pinjam/views.py
from django.shortcuts import render
from django.db import connection
from django.core.paginator import Paginator

def pinjam(request):
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to komik;"
                       "SELECT kode, no_anggota, jumlah_komik, durasi_pinjam, total_biaya, tanggal_pinjam, tanggal_kembali, tanggal_dikembalikan "
                       "FROM transaksi_pinjam;")
        data_pinjam = dictfetchall(cursor)
    paginator = Paginator(data_pinjam, 10)
    page = request.GET.get('page')
    data = paginator.get_page(page)
    for d in data_pinjam:
        if(d['tanggal_dikembalikan'] <= d['tanggal_kembali']):
            d['status'] = 'Selesai'
        else:
            d['status'] = 'Belum'
    return render(request, "transaksi_pinjam.html", {'data_pinjam' : data})

def baca(request):
    return render(request, "transaksi_baca.html")

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

produk/views.py
from django.shortcuts import render
from django.db import connection
from django.core.paginator import Paginator

def index(request):
    with connection.cursor() as cursor:
        cursor.execute("SET search_path to komik;"
                       "SELECT id, nama, jumlah, tipe_produk "
                       "FROM produk;")
        data_produk = dictfetchall(cursor)
    paginator = Paginator(data_produk, 10)
    page = request.GET.get('page')
    data = paginator.get_page(page)
    return render(request, "daftar_produk.html", {'data_produk' : data})

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'homepage.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Baskervville&display=swap" rel="stylesheet">
    <title>Hello, world!</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light sikomik" sty>
        <a class="navbar-brand" style="font-family: 'Baskervville', serif; font-weight: bold;" href="/">si<span style="color: green;">komik</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active sikomik" href="/">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link sikomik" href="/anggota/">Anggota</a>
            <a class="nav-item nav-link sikomik" href="/produk/">Produk</a>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Transaksi
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/transaksi/baca">Baca</a>
                  <a class="dropdown-item" href="/transaksi/pinjam">Pinjam</a>
              </li>
          </div>
          <div class="navbar-nav ml-auto sikomik">
            <form action="{% url 'authentication:login_form' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Submit">
            </form>
          </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</body>

</html>

templates/daftar_anggota.html
{% extends 'base.html' %}}
{% block content %}
<div class='jumbotron'>
    <div class="pagination">
            <span class="step-links sikomik">
                {% if data_anggota.has_previous %}
                    <a href="?page=1" style='color:black; font-weight: bold;'>&laquo; first</a>
                    <a href="?page={{ data_anggota.previous_page_number }}" style='color:green;'>previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ data_anggota.page_number }} of {{ data_anggota.paginator.num_pages }}.
                </span>
        
                {% if data_anggota.has_next %}
                    <a href="?page={{ data_anggota.next_page_number }}" style='color:green;'>next</a>
                    <a href="?page={{ data_anggota.paginator.num_pages }}" style='color:green;'>last &raquo;</a>
                {% endif %}
            </span>
        </div>
        <table class="table" id="tabelpeminjaman">
                <thead>
                <tr>
                    <th>No. Anggota</th>
                    <th>Id</th>
                    <th>Nama</th>
                    <th>Alamat</th>
                    <th>Tanggal Lahir</th>
                    <th>No. HP</th>
                </tr>
                </thead>
                <tbody>
                {% for anggota in data_anggota %}
                <tr>
                    <td>{{ anggota.no_anggota }}</td>
                    <td>{{ anggota.id }}</td>
                    <td>{{ anggota.nama }}</td>
                    <td>{{ anggota.alamat }}</td>
                    <td>{{ anggota.tanggal_lahir }}</td>
                    <td>{{ anggota.no_hp }}</td>

                </tr>
                {% endfor %}
                </tbody>
            </table>
</div>
{% endblock %}

templates/daftar_komik.html
{% extends 'base.html' %}}
{% block content %}
    <table class="table" id="tabelpeminjaman">
        <thead>
        <tr>
            <th>Id</th>
            <th>Nama</th>
        </tr>
        </thead>
        <tbody>
        {% for komik in data_komik %}
        <tr>
            <td>{{ komik.id }}</td>
            <td>{{ komik.nama }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/daftar_produk.html
{% extends 'base.html' %}}
{% block content %}
<div class='jumbotron'>
        <h2 class="sikomik" style="font-size: 1em; background-color grey;">Tidak ada kolom jumlah available karena ternyata table dari komik tidak sinkron dengan tabel yang ada di produk</h2>
    <div class="pagination">
            <span class="step-links sikomik">
                {% if data_produk.has_previous %}
                    <a href="?page=1" style='color:green;'>&laquo; first</a>
                    <a href="?page={{ data_produk.previous_page_number }}" style='color:green;'>previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ data_produk.id }} of {{ data_produk.paginator.num_pages }}.
                </span>
        
                {% if data_produk.has_next %}
                    <a href="?page={{ data_produk.next_page_number }}" style='color:green;'>next</a>
                    <a href="?page={{ data_produk.paginator.num_pages }}" style='color:green;'>last &raquo;</a>
                {% endif %}
            </span>
        </div>
    <table class="table" id="tabelpeminjaman">
        <thead>
        <tr class='sikomik' style='color:green; font-weight: 800;'>
            <th>id</th>
            <th>Nama</th>
            <th>jumlah</th>
            <th>tipe_produk</th>
        </tr>
        </thead>
        <tbody>
        {% for produk in data_produk %}
        <tr>
            <td>{{ produk.id }}</td>
            <td>{{ produk.nama }}</td>
            <td>{{ produk.jumlah }}</td>
            <td>{{ produk.tipe_produk }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/homepage.html
{% extends 'base.html' %}}
{% block content %}
<div class="jumbotron sikomik" style="margin: 5% 5%;">
    <h1 class="display-4" style="color: green;">Halo!</h1>
    <p class="lead">Website ini masih belum jadi</p>
    <hr class="my-4">
    <p>Rencananya website ini akan dipakai untuk menyewa komik.</p>
    <p>Yuk, lihat list semua komik yang ada!.</p>
    <a class="btn btn-primary btn-lg" href="produk" role="button" style="background-color:white; border-color: lightgreen; color: black;">Lihat Komik</a>
  </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}}
{% block content %}
<form>
    <div class='jumbotron'>
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
        </div>
    </div>
    
    {% endblock %}

templates/transaksi_baca.html
{% extends 'base.html' %}}
{% block content %}
<div class="jumbotron sikomik" style="margin: 5% 5%;">
    <h1 class="display-4" style="color: green;">Halo!</h1>
    <h2 class="display-5">Halaman ini belum ada karena tabel transaksi baca ternyata belum dibuat di tahap sebelumnya</h2>
    <a class="btn btn-primary btn-lg" href="produk" role="button" style="background-color:white; border-color: lightgreen; color: black;">Lihat Komik</a>
  </div>
{% endblock %}

templates/transaksi_pinjam.html
{% extends 'base.html' %}}
{% block content %}
    <div class='jumbotron'>
        <div class="pagination">
                <span class="step-links sikomik">
                    {% if data_pinjam.has_previous %}
                        <a href="?page=1" style='color:green;'>&laquo; first</a>
                        <a href="?page={{ data_pinjam.previous_page_number }}" style='color:green;'>previous</a>
                    {% endif %}
            
                    <span class="current">
                        Page {{ data_pinjam.id }} of {{ data_pinjam.paginator.num_pages }}.
                    </span>
            
                    {% if data_pinjam.has_next %}
                        <a href="?page={{ data_pinjam.next_page_number }}" style='color:green;'>next</a>
                        <a href="?page={{ data_pinjam.paginator.num_pages }}" style='color:green;'>last &raquo;</a>
                    {% endif %}
                </span>
            </div>
            <table class="table" id="tabelpeminjaman">
                <thead>
                <tr>
                    <th>No. Anggota</th>
                    <th>Komik</th>
                    <th>Durasi Pinjam</th>
                    <th>Total Biaya</th>
                    <th>Tanggal Pinjam</th>
                    <th>Tanggal Kembali</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>
                {% for t in data_pinjam %}
                <tr>
                    <td>{{ t.no_anggota }}</td>
                    <td>{{ t.jumlah_komik }}</td>
                    <td>{{ t.durasi_pinjam }} hari</td>
                    <td>{{ t.total_biaya }}</td>
                    <td>{{ t.tanggal_pinjam }}</td>
                    <td>{{ t.tanggal_kembali }}</td>
                    <td>{{ t.status }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
    </div>
{% endblock %}